menu_script = {"Long ago, there was a thriving, snakey, alien race called the Sneeks.",
"They had a beautiful home planet, called Snook.",
"But one fateful day, an asteroid was spotted heading for their planet.",
"Thankfully, all the Sneeks escaped, but their home was no more.",
"So, the king Sneek began his search for a new home.",
"After many years of searching, they finally found Earth.",
"However, Earth was inhabited by Humans, a comparatively primitive race to the Sneeks.",
"Thus, the king Sneek decided to conquer Earth,",
"as the Sneeks to this point had no concept of friendship."  ,
"At first he thought of a full scale attack,",
"but his officers ruled against that.",
"They decided to instead abduct a Human to see if that was possible.",
"And that is where you come in.",
"You have been abducted by the Sneeks.",
"You must escape their spaceship,",
"You must convince them not to invade Earth.",
"And save humanity from perishing"}
