text = {"-- Guard 1",
"Guard 1 approaches!",
"Guard 1: Attack 10{n}A very easy enemy",
"Insult",
"You told Guard 1 that he was keeping you from your goals.{n}He got more upset",
"You told Guard 1 that he wasn't snakey enough.{n}He got more upset",
"Compliment",
"You told Guard 1 that he was good at his job.{n}He became very happy.",
"You told Guard 1 that his snakeyness was enough to become a guard{n}He became very happy.",
"You befriended Guard 1{n}He dropped a keycard",
"-- Guard 2",
"Guard 2 approaches!",
"Guard 2: Attack 15{n}Its a guard boi",
"Cheer",
"You told Guard 2 that you hate humans too{n}He is fine with your existence now",
"You told Guard 2 that your fine with Sneeks{n} He is fine with you now",
"Talk",
"You told Guard 2 that you defeated Guard 1{n}That was pretty obvious",
"You told Guard 2 that humans are kind{n}He chuckles",
"You befriended Guard 2{n}He dropped a keycard",
"-- Guard 3",
"Guard 3 approaches!",
"Guard 3: Attack 20{n}Learn how walls work ... fast",
"Poke",
"You poke Guard 3{n}That was mean",
"You poke Guard 3 very hard{n}He considers raising his attack",
"Honor",
"You tell Guard 3 you respect him{n}He likes you more than he did",
"You tell Guard 3 you don't mind if he wins{n}He respects that",
"You befriended Guard 3{n}He dropped a keycard",
"--Items",
"Your inventory is full!",
"--Shield Text",
"You picked up a Shield!",
"Defense: 10%{n}You equiped a shield!",
"--Health Potion",
"You picked up a Health Potion!",
"You drank a health potion!{n}You gained 10 HP",
"--Blue Keycard",
"You picked up the Blue Keycard",
"You can't use a keycard in battle!",
"--Red Keycard",
"You picked up the Red Keycard",
"--Green Keycard",
"You picked up the Green Keycard",
"--Guard 4",
"Guard 4 is ticked!",
"Guard 4: Attack 20{n}How on earth did you escape the cells",
"Talk",
"You talk to Guard 4 about the weather{n}He seems chill",
"There is nothing new to talk to Guard 4 about",
"Gift",
"Why would you give a gift to someone you haven't talked to{n}Weirdo",
"Guard 4 has gotten to know you{n}He accepts your gift",
"Guard 4 is now your best friend!{n}He lets you go to the final escape pod!",
"I'm suprised you made it this far",
"Our species has fallen from grace",
"You annoying humans with your luxurious planet",
"{fast_appear}{shake}I{/}{fast_appear}t {shake}e{/}{fast_appear}nds {shake}n{/}{fast_appear}ow!",
"You humans fight valiantly, you really do",
"However, no one defeats the king of the Sneeks!",
"I will fight you to the death!",
"If you somehow manage to kill me, my Guards will let you into the escape pods",
"and they will not invade your beautiful planet",
"However! If you loose",
"Well{slow_appear}...{/}You'll be dead",
"And Humanity will perish!",
"And the Sneeks will once again rise to power!",
"{shake}GUARDS! SEIZE THIS HUMAN",
"The king has no mercy{n}You feel trapped",
"King: Attack 15{n}He really needs some persuasion",
"Persuade",
"You argue that Humans and Sneeks can live together{n}That did little help",
"You argue that there are other planets besides earth{n}He thinks a little",
"You argue that Earth has its own problems{n}He doesn't want to belive you",
"You argue that Humans are nice creatures{n}He can belive that",
"{cannot_skip}Before you speak{n}the king admits he doesn't want to kill you",
"The king can not hear you{n}You need to get closer",
"Stand",
"You tell the king you will not move{n}He gets increasingly annoyed",
"{cannot_skip_slower}...",
"It appears I was wrong",
"Very Very Wrong",
"Humans are not the ruthless entities I thought they were",
"They can be nice",
"Go home and continue your life",
"But please don't be mean like us Sneeks",
"Spread kindness to your humans",
"And your planet will prosper and live on",
"Take that escape pod and go home",
"However please, go home and enjoy your life my dear human",
"I'm sure we will meet again",
"{cannot_skip_faster}Its Time",
"--Blue Heal",
"You picked up a Blue Potion!",
"You drank the blue potion!{n}You gained 30 HP",
"Stand over an item and press{red} Enter{/} to pick it up",
"{red}Walls{/} can block projectiles",
"Use a {red}lock{/} like you use a sign."
}